name: flutter_shuttletracker
description: Flutter ShuttleTracker is a cross-platform port of ShuttleTracker
  that utilizes the Flutter SDK for development.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc_test: ^8.0.0
  connectivity: ^3.0.3
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_map: ^0.12.0
  flutter_svg: ^0.19.3
  geolocator: ^7.0.1
  http: ^0.13.1
  hydrated_bloc: ^7.0.0
  path_provider: ^2.0.1
  responsive_framework: ^0.1.0
  scrollable_positioned_list: ^0.1.10
  shared_preferences: ^2.0.5
  url_launcher: ^6.0.2
  web_socket_channel: ^2.0.0

dev_dependencies:
  effective_dart: ^1.3.1
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/student_union.jpg
    - assets/img/logo.png
    - assets/img/circle.png
    - assets/img/stop.png
    - assets/img/shuttle.svg
    - assets/img/stop_thin.png
    - assets/img/dark_stop.png
    - assets/img/selected_stop.png
    - assets/img/user.png
    - assets/json_test/routes.json
    - assets/json_test/stops.json
    - assets/json_test/updates.json

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/shuttle_icon.ttf
