name: flutter_shuttletracker
description: Flutter ShuttleTracker is a cross-platform port of ShuttleTracker
  that utilizes the Flutter SDK for development.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc_test: ^9.0.2
  connectivity: ^3.0.6
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_map: ^0.14.0
  flutter_svg: ^1.0.0
  geolocator: ^8.0.1
  http: ^0.13.4
  hydrated_bloc: ^8.0.0
  path_provider: ^2.0.8
  responsive_framework: ^0.1.5
  scrollable_positioned_list: ^0.2.3
  shared_preferences: ^2.0.12
  url_launcher: ^6.0.18
  web_socket_channel: ^2.1.0

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  effective_dart: ^1.3.2
  pedantic: ^1.11.1
  flutter_native_splash: ^1.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/img/student_union.jpg
    - assets/img/logo.png
    - assets/img/circle.png
    - assets/img/stop.png
    - assets/img/shuttle.svg
    - assets/img/stop_thin.png
    - assets/img/dark_stop.png
    - assets/img/selected_stop.png
    - assets/img/user.png
    - assets/json_test/routes.json
    - assets/json_test/stops.json
    - assets/json_test/updates.json

  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/shuttle_icon.ttf
