name: flutter_shuttletracker
description: Flutter ShuttleTracker is a cross-platform port of ShuttleTracker that utilizes the Flutter SDK for development.

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  device_preview: ^0.4.8
  connectivity: ^2.0.1
  flutter_cupertino_settings: ^0.3.1
  scrollable_positioned_list: ^0.1.8
  hydrated_bloc: ^6.0.3
  shared_preferences: ^0.5.12+4
  flutter_native_splash: ^0.1.9
  flutter_platform_widgets: ^0.70.2
  flutter_widget_from_html: ^0.5.1+4
  observable: ^0.22.2
  flutter_svg: ^0.19.1
  flutter_bloc: ^6.1.0
  equatable: ^1.2.5
  responsive_framework: ^0.0.11
  http: ^0.12.2
  flutter_map: ^0.10.1  
  geolocation: ^1.1.2
  loading: ^1.0.2
  web_socket_channel: ^1.1.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_launcher_icons: "^0.7.5"
  effective_dart: ^1.2.1
  pedantic: ^1.9.0
  # flutter_test:
  #   sdk: flutter

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/img/app_icon.png"

flutter_native_splash:
  image: "assets/img/logo.png"
  color: "ffffff"


flutter:

  uses-material-design: true

  assets:
    - assets/img/student_union.jpg
    - assets/img/logo.png
    - assets/img/circle.png
    - assets/img/stop.png
    - assets/img/shuttle.svg
    - assets/img/stop_thin.png
    - assets/img/dark_stop.png
    - assets/img/selected_stop.png
    - assets/img/user.png
    - assets/json_test/routes.json
    - assets/json_test/stops.json
    - assets/json_test/updates.json
  
  fonts:
    - family: CustomIcons
      fonts:
          - asset: assets/fonts/shuttle_icon.ttf